- name: Check if template exists
  ansible.builtin.stat:
    path: "/var/lib/vz/template/cache/{{ lxc_template }}"
  register: template_stat

- name: Download linux template in lxc_template
  ansible.builtin.shell:
    cmd: "pveam download local {{ lxc_template }}"
    creates: "/var/lib/vz/template/cache/{{ lxc_template }}"
  register: download_result
  when: not template_stat.stat.exists

- name: Verify template download
  ansible.builtin.stat:
    path: "/var/lib/vz/template/cache/{{ lxc_template }}"
  register: verify_stat

- name: Fail if template is not downloaded
  ansible.builtin.fail:
    msg: "Template download failed!"
  when: not verify_stat.stat.exists

