- name: Create Caddy container on local Proxmox server
  hosts: proxmox
  remote_user: root 
  gather_facts: false
  become: true
  vars:
    lxc_template: "{{ ubuntuTemplate }}"
    container_name: "caddy"
    container_vmid: 240

  roles:
    - setupPythonEnvAndInstallPackagesOnProxmox
    - downloadLinuxTemplateOnProxmox
    - createStandardLxc
    - addStandardFirewall
    - setupLxcInternet
