- name: Create LXC container on local Proxmox server
  hosts: proxmox
  remote_user: root 
  gather_facts: false
  become: true
  vars:
    proxmox_host: "proxmox"  # Proxmox API on localhost
    proxmox_user: "root@pam"
    proxmox_node: "proxmox" # for me, its just the host name
    proxmox_password: "{{ lookup('ansible.builtin.env', 'PROXMOX_PASSWORD') }}"
    lxc_template: "local:vztmpl/ubuntu-24.10-standard_24.10-1_amd64.tar.zst" # path gotten from command "pvesh get /nodes/proxmox/storage/local/content"
    container_name: "learnToLineDance"
    container_vmid: 241
    gateway_ip: "192.168.1.1"

  roles:
    - setupPythonEnvAndInstallPackagesOnProxmox
    - installUbuntuOnProxmox
    - createStandardLxc
    - addStandardFirewall
    - setupLxcInternet
