- name: Create LXC container on local Proxmox server
  hosts: proxmox
  remote_user: root 
  gather_facts: false
  become: true
  vars:
    lxc_template: "{{ ubuntuTemplate }}"
    container_name: "learnToLineDance"
    container_vmid: 241

  roles:
    - setupPythonEnvAndInstallPackagesOnProxmox
    - downloadLinuxTemplateOnProxmox
    - createStandardLxc
    - addStandardFirewall
    - setupLxcInternet
