- name: Create LXC container on local Proxmox server
  hosts: proxmox
  remote_user: root 
  gather_facts: false
  become: true
  vars:
    lxc_template: "local:vztmpl/ubuntu-24.10-standard_24.10-1_amd64.tar.zst" # path gotten from command "pvesh get /nodes/proxmox/storage/local/content"
    container_name: "ale-tavern-server"
    container_vmid: 242

  roles:
    - setupPythonEnvAndInstallPackagesOnProxmox
    - installUbuntuOnProxmox
    - createStandardLxc
    - addStandardFirewall
    - setupLxcInternet
