- name: Create LXC container on local Proxmox server
  hosts: proxmox
  remote_user: root 
  gather_facts: false
  become: true
  vars:
    lxc_template: "{{ debianTemplate }}"
    container_name: "minecraft-bedrock"
    container_vmid: 244 # need to open minecraft port on router both upd and tcp + change host below + add fw + add host
    # disk_size: 20
    memory: 20000
    cores: 8

  roles:
    - setupPythonEnvAndInstallPackagesOnProxmox
    - downloadLinuxTemplateOnProxmox
    - createStandardLxc
    - addStandardFirewall
    - setupLxcInternet

#  tasks:
#    - name: Pause for 20 seconds for network to be setup
#      ansible.builtin.pause:
#        seconds: 20

- name: Setup minecraft container
  hosts: minecraft-bedrock  # <--------------------------------------------------------- DONT FORGET TO CHANGE THIS
  remote_user: root
  gather_facts: false
  become: true
  vars:
    minecraft_dir: "minecraft"

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install screen package
      apt:
        name: screen
        state: present

    - name: Install unzip
      apt:
        name: unzip
        state: present

    - name: Install libcurl needed for bedrock
      apt:
        name: libcurl4
        state: present

    - name: Download Oracle JDK 21 Debian package
      get_url:
        url: "https://download.oracle.com/java/21/latest/jdk-21_linux-x64_bin.deb"
        dest: "/opt/jdk-21_linux-x64_bin.deb"
        mode: '0644'

    - name: Install Oracle JDK 21
      command: dpkg -i /opt/jdk-21_linux-x64_bin.deb
      args:
        chdir: /opt

    - name: Create Minecraft directory
      file:
        path: "{{ minecraft_dir }}"
        state: directory
        mode: '0755'

    - name: Download Bedrock Minecraft server zip
      get_url:
        url: "https://www.minecraft.net/bedrockdedicatedserver/bin-linux/bedrock-server-1.21.62.01.zip"
        dest: "{{ minecraft_dir }}/bedrock-server-1.21.62.01.zip"
        mode: '0755'

    - name: Check if Minecraft screen session exists
      shell: screen -ls | grep -q "minecraft"
      register: minecraft_screen_check
      ignore_errors: true

    - name: Unarchive server download
      ansible.builtin.unarchive:
        src: "{{ minecraft_dir }}/bedrock-server-1.21.62.01.zip"
        dest: "{{ minecraft_dir }}"
        remote_src: yes

    - name: Make server normal
      lineinfile:
        path: "{{ minecraft_dir }}/server.properties"
        regexp: '^difficulty='
        line: 'difficulty=normal'
      when: minecraft_screen_check.rc != 0

    - name: Allow more players
      lineinfile:
        path: "{{ minecraft_dir }}/server.properties"
        regexp: '^max-players='
        line: 'max-players=50'
      when: minecraft_screen_check.rc != 0

    - name: Start Minecraft
      command: screen -dmS minecraft ./bedrock_server
      args:
        chdir: "{{ minecraft_dir }}"
      ignore_errors: true
      when: minecraft_screen_check.rc != 0


