- name: Create Caddy container on local Proxmox server
  hosts: proxmox
  remote_user: root 
  gather_facts: false
  become: true
  vars:
    proxmox_host: "proxmox"  # Proxmox API on localhost
    proxmox_user: "root@pam"
    proxmox_node: "proxmox" # for me, its just the host name
    proxmox_password: "{{ lookup('ansible.builtin.env', 'PROXMOX_PASSWORD') }}"
    lxc_template: "{{ ubuntuTemplate }}"
    container_name: "caddy"
    container_vmid: 240
    gateway_ip: "192.168.1.1"

  roles:
    - setupPythonEnvAndInstallPackagesOnProxmox
    - installUbuntuOnProxmox
    - createStandardLxc
    - addStandardFirewall
    - setupLxcInternet
