- name: Install unity on container
  hosts: unity_builder
  tasks:
    - name: Download unity version # From https://unity.com/releases/editor/whats-new/2022.3.0#installs
      ansible.builtin.get_url:
        url: https://download.unity3d.com/download_unity/fb119bb0b476/LinuxEditorInstaller/Unity-2022.3.0f1.tar.xz
        dest: /tmp/unity.tar
