---
- name: Setup LXC Internet in container {{ container_id }}
  hosts: localhost
  become: yes
  vars:
    # Define a default container_id; you can override this when running the playbook.
    container_id: 242
  tasks:
    - name: Check if /etc/resolv.conf in container already has nameserver 8.8.4.4
      command: pct exec {{ container_id }} -- grep "nameserver 8.8.4.4" /etc/resolv.conf
      register: resolv_conf_check
      ignore_errors: yes

    - name: Configure container networking and add nameserver if missing
      block:
        - name: Add IP address to eth0 in container
          command: pct exec {{ container_id }} -- ip addr add 192.168.1.{{ container_id }}/24 dev eth0

        - name: Bring eth0 up in container
          command: pct exec {{ container_id }} -- ip link set eth0 up

        - name: Add default route in container
          command: pct exec {{ container_id }} -- ip route add default via 192.168.1.1

        - name: Append nameserver to /etc/resolv.conf in container
          command: pct exec {{ container_id }} -- sh -c "echo 'nameserver 8.8.4.4' >> /etc/resolv.conf"
      when: resolv_conf_check.rc != 0
